# Define version
version: 1

# Define your URLs (Mandatory!)
# URLs should start with - (remove the comment symbol #)
# Replace the values with your tokens/ids
# For example a telegram URL would look like:
# - tgram://123456789:AABx8iXjE5C-vG4SDhf6ARgdFgxYxhuHb4A/-606743502
urls:
  - tgram://2144566768:AAH4_3p9eEKliHuTY86AzS7H-mcA3tvutIo
  # - discord://WebhookID/WebhookToken/
  # - slack://tokenA/tokenB/tokenC
  # More options here: https://github.com/caronc/apprise
